services:
  - type: web
    name: linguaquest-api
    runtime: python  
    plan: free
    buildCommand: "cd backend && pip install -r requirements-optimized.txt"
    startCommand: "cd backend && python production_start.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:///./linguaquest.db
      - key: CORS_ORIGINS
        value: "*"
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
    # Add restart policy to keep service alive
    scaling:
      minInstances: 1
      maxInstances: 1
