services:
  - type: web
    name: linguaquest-api
    runtime: python  
    plan: free
    buildCommand: "cd backend && pip install -r requirements-optimized.txt"
    startCommand: "cd backend && python start.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:///./linguaquest.db
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /health
